name: tubes_pbp_6
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  image_picker: ^0.8.4+4
  motion_tab_bar : ^2.0.4
  shared_preferences: ^2.0.13

dev_dependencies:
  camera: ^0.10.5+2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mobile_scanner: ^3.2.0 
  path_provider: ^2.0.15 
  qr_flutter: ^4.1.0 

flutter:
  uses-material-design: true
  
  assets:
    - images/download.jpg
    - images/download1.jpg
    - images/gambar1.png
    - images/gambar3.jpg
    - lib/assets/preLoginAsset/Logo.jpg
    - lib/assets/preLoginAsset/orangPreLogin.png
    - images/download.jpg
    - images/zumba.jpg
    - images/aerobic.jpg
    - images/boxing.jpg
    - images/pilates.jpg
    - images/lifting.jpg
    - images/dance.jpg
    - images/yoga.jpg
    - lib/assets/preLoginAsset/Logo.jpg
