name: tubes_pbp_6
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - images/download.jpg
    - images/zumba.jpg
    - images/aerobic.jpg
    - images/boxing.jpg
    - images/pilates.jpg
    - images/lifting.jpg
    - images/dance.jpg
    - images/yoga.jpg
    - lib/assets/preLoginAsset/Logo.jpg